(function () {
    var words = [
        'Stay home',
        'Quedarse en casa',
        'Stare a casa',
        'ねえ',
        'Zu Hause bleiben',
        '呆在家里',
        '呆在家裡',
        'Rester à la maison',
        'در خانه بمان',
        'Evde kal',
        'Blijf thuis',
        'Zu Hause bleiben',
        'Blijf thuis',
        'Ficar em casa',
        'Zu Hause bleiben',
        'Ficar em casa',
        '집에있어 라',
        'להישאר בבית',
        'Остаться дома',
        'Stanna hemma',
        'Bli hjemme',
        'Stay home',
        'Fan abhaile',
        'Bliv hjemme',
        'घर पर रहना',
        'Quedarse en casa',
        'Zůstat doma',
        'Zostań w domu',
        'Stai acasă',
        '家にいる',
        'Tinggal di rumah',
        'گھر رہنا',
        'Quedarse en casa',
        'Manatili sa bahay',
        'Bleift doheem',
        'Tinggal di rumah',
        'Quedarse en casa',
        'ابق في المنزل',
        'Quedarse en casa',
        'ابق في المنزل',
        'Jäädä kotiin',
        'Останем код куће',
        'อยู่บ้าน',
        'Quedarse en casa',
        'ابق في المنزل',
        'Quedarse en casa',
        'Μείνε σπίτι',
        'Quedarse en casa',
        'Bly tuis',
        'Tinggal di rumah',
        'Vertu heima',
        'ابق في المنزل',
        'ابق في المنزل',
        'Ostati kod kuće',
        'Jää koju',
        'ابق في المنزل',
        'Ostani doma',
        'Застацца дома',
        'Stai acasă',
        'Li malê bimîne',
        'Kia noho ki te kainga',
        '呆在家里',
        'Likti namuose',
        'Otthon maradni',
        'Մնալ տանը',
        'ابق في المنزل',
        'ابق في المنزل',
        'Ostani kod kuće',
        'Evdə qalmaq',
        'Үйде бол',
        'Rester à la maison',
        'ابق في المنزل',
        'Остани дома',
        'Остани у дома',
        'Zostať doma',
        'Palikt mājās',
        'ابق في المنزل',
        'Quedarse en casa',
        'Quedar-se a casa',
        'Uyda qoling',
        'Μείνε σπίτι',
        'Quedarse en casa',
        'Quedarse en casa',
        'کور کې پاتې شه',
        'ابق في المنزل',
        'Qendro ne shtepi',
        'Quedarse en casa',
        'Rester à la maison',
        '呆在家裡',
        'Rester à la maison',
        'ابق في المنزل',
        'Rester à la maison',
        'Quedarse en casa',
        'Ibqa d-dar',
        'Stay Home',
        'Stare a casa',
        'Rester à la maison',
        'Үйдө кал',
        'Stay home',
        'ابق في المنزل',
        'Stay home',
        'Ở nhà',
        'Crnogorski',
        'Rester à la maison',
        'বাড়িতে থাকুন',
        'Quedarse en casa',
        'დარჩი სახლში',
        'ගෙදර ඉන්න',
        'Bliv hjemme',
        'Qendro ne shtepi',
        'Rester à la maison',
        'Kaa nyumbani',
        'Rester à la maison',
        'Stay home',
        'Quedarse en casa',

        'Rester à la maison',
        'Rester à la maison',
        'Rester à la maison',
        'Tinggal di rumah',
        'Stay home',
        'Quedarse en casa',

        'Guma murugo',
        'Quedarse en casa',
        'Rester à la maison',
        'Mijanona ao an-trano',
        'Rester à la maison',
        'Zu Hause bleiben',
        'Quedarse en casa',
        'Blijf thuis',
        'Rester à la maison',
        'Rester à la maison',

        'Rester à la maison',
        'ቤት ቆይ',
        'Beera eka',
        'Rester à la maison',

        'Rester à la maison',
        'Ficar em casa',


        'Ficar em casa',
        'ቤት ጽናሕ',
        'Ficar em casa',
        'Rester à la maison',
        'Rete lakay ou',
        'Kaa nyumbani',
        'အိမ်မှာနေပါ',
        'ابق في المنزل',
        'Stay home',
        'hunna hurun ge',
        'ابق في المنزل',
        'Rester à la maison',
        'Ficar em casa',
        'Bly tuis',
        'Quedarse en casa',
        'tiko e vale',
        'Гэртээ байх',
        'Cicing di bumi',

        'ຢູ່ບ້ານ',
        'Stay home',
        'Blijf thuis',
        'Stay home',
        'Gara kumba',
        'Rester à la maison',
        'Stay home',
        'Blijf thuis',
        'Stay home',
        'bahlala Umndeni',
        'Ficar em casa',
        'Rester à la maison',
        'घरमै बस',
        'Guriga joog',
        'Rester à la maison',
        'Sede in domo tua',
        'Ficar em casa',
        'Stay home',
        'emisa gae',
        'Rester à la maison',
        'ابق في المنزل ',
    ], i = 0;
    setInterval(function () {
        $('#changingword').fadeOut(function () {
            $(this).html(words[i = (i + 1) % words.length]).fadeIn();

        });
    }, 1500);

})();



